@startuml
!$COLOR_INDEX_0="#FCFBFD"
!$COLOR_INDEX_1="#EFEDF5"
!$COLOR_INDEX_2="#DADAEB"
!$COLOR_INDEX_3="#BCBDDC"
!$COLOR_INDEX_4="#9E9AC8"
!$COLOR_INDEX_5="#807DBA"
!$COLOR_INDEX_6="#6A51A3"
!$COLOR_INDEX_7="#54278F"
!$COLOR_INDEX_8="#3F007D"
!$COLOR_BORDER="#000000"

<style>
root {
    FontName Verdana
    FontSize 12
    FontColor $COLOR_INDEX_0
}

actor, participant {
    BackgroundColor $COLOR_INDEX_6
    BorderColor $COLOR_BORDER
    FontColor $COLOR_BORDER
    FontSize 12
}

participant {
    BackgroundColor $COLOR_INDEX_4
}

usecase {
    BackgroundColor $COLOR_INDEX_6
    BorderColor $COLOR_BORDER
    FontColor $COLOR_INDEX_0
    FontSize 12
}

class, component, node {
    BackgroundColor $COLOR_INDEX_6
    LineColor $COLOR_INDEX_0
    BorderColor $COLOR_BORDER
    FontColor $COLOR_INDEX_0
    FontSize 12
}

package {
    BackgroundColor $COLOR_INDEX_2
    BorderColor $COLOR_BORDER
    FontColor $COLOR_BORDER
    BorderThickness 2
}

rectangle, control, entity, database, collections, queue {
    BackgroundColor $COLOR_INDEX_4
    BorderColor $COLOR_BORDER
    FontColor $COLOR_BORDER
}

note {
    BorderColor $COLOR_BORDER
    FontColor $COLOR_BORDER
}

arrow {
    Color $COLOR_BORDER
    FontColor $COLOR_BORDER
    FontSize 12
    Thickness 2
}

legend {
    BackgroundColor $COLOR_INDEX_2
    BorderColor $COLOR_BORDER
    FontColor $COLOR_BORDER
    FontSize 10
}
</style>

skinparam DefaultTextAlignment center

@enduml
