name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: '22'
          - os: macos-latest
            node-version: '22'
          - os: windows-latest
            node-version: '22'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./minefinder-web
        run: npm ci

      - name: Lint
        working-directory: ./minefinder-web
        run: npm run lint
        continue-on-error: true

      - name: Build web app
        working-directory: ./minefinder-web
        run: npm run build

      - name: Build desktop app
        working-directory: ./minefinder-web
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            npm run build:linux
          elif [ "$RUNNER_OS" == "macOS" ]; then
            npm run build:mac
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm run build:win
          fi
        shell: bash

      - name: Upload Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./minefinder-web/dist/*.AppImage
            ./minefinder-web/dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./minefinder-web/dist/*.dmg
            ./minefinder-web/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./minefinder-web/dist/*.exe
            ./minefinder-web/dist/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}